spring.application.name=globessza
spring.datasource.url=jdbc:mysql://database-1.cansis08qh9w.us-east-1.rds.amazonaws.com:3306/Globessza
spring.datasource.username=admin
spring.datasource.password=Globessza2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true